### ISSUE TITLE
Emacs calls doom incorrectly

### ISSUE THREAD

**Issue by thecaralice** [marienz/nix-doom-emacs-unstraightened#40]
Commands like SPC-h-r-r call the original doom with EMACS pointing to the original Emacs, which causes obscure issues. I patched doomemacs while debugging an issue I had to call my debugging utility instead of doom, here's the result:
```yaml
Arguments: [
    "mole", # this is the argv[0]
    "/nix/store/09391jc8xazy2mrjhmca0xzblrmxm9iz-source/bin/doom", # this would be the argv[0]
    "sync",
    "-B",
    "-e",
]

Environment: {
    "DOOMDIR": "/Users/alice/.config/doom/",
    "DOOMLOCALDIR": "/Users/alice/.local/share/nix-doom/",
    "DOOMPROFILE": "nix",
    "DOOMPROFILELOADFILE": "/nix/store/r5xp99h6bs20cb5d3b49xk6jarnvj0d9-doom-profile/loader/init.el",
    "EMACS": "/nix/store/ysr370j2nylqbvwmnk2y3w2hfm0w09ky-emacs-pgtk-29.4/bin/emacs",
    "EMACSDIR": "/nix/store/09391jc8xazy2mrjhmca0xzblrmxm9iz-source/",
    "EMACSLOADPATH": "",
    "EMACSNATIVELOADPATH": "",
    "INSIDE_EMACS": "29.4,comint",
    "OLDPWD": "/nix/store/09391jc8xazy2mrjhmca0xzblrmxm9iz-source",
    "PATH": "/nix/store/wixmy825ga0mzv5ic5k7p471n8760c8b-mole-0.0.1/bin:/Users/alice/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin",
    "PWD": "/nix/store/09391jc8xazy2mrjhmca0xzblrmxm9iz-source",
    # irrelevant variables omitted
}
```

Passing these EMACS and DOOMLOCALDIR to that doom executable is enough to reproduce the issue I had with SPC-h-r-r:

```shellsession
$ DOOMLOCALDIR=/Users/alice/.local/share/nix-doom/ EMACS=/nix/store/ysr370j2nylqbvwmnk2y3w2hfm0w09ky-emacs-pgtk-29.4/bin/emacs /nix/store/09391jc8xazy2mrjhmca0xzblrmxm9iz-source/bin/doom sync -B -e
- Using Emacs 29.4 @ /nix/store/ysr370j2nylqbvwmnk2y3w2hfm0w09ky-emacs-pgtk-29.4/bin/emacs
> Synchronizing "default" profile...
  x There was an unexpected runtime error
    Message: File is missing
    Details: ("Cannot open load file" "No such file or directory" "straight")
    Backtrace:
      (require straight)
      (nix-doom-skip-core-packages nil)
      (apply nix-doom-skip-core-packages nil)
      (doom-initialize-core-packages nil)
      (doom-initialize-packages)
      (doom-packages-ensure nil)
      (let ((doom-print-level (or nil doom-print-level)) (doom-print-indent ...
      (progn (let ((doom-print-level (or nil doom-print-level)) (doom-print-...
      (unwind-protect (progn (let ((doom-print-level (or nil doom-print-leve...
      (let ((noenvvar? (cdr (assq 'noenvvar? alist))) (update? (cdr (assq 'u...
      ((closure (t) (cli alist) (let ((noenvvar? (cdr (assq 'noenvvar? alist...
      (funcall (closure (t) (cli alist) (let ((noenvvar? (cdr (assq 'noenvva...
GNU Emacs     v29.4            nil
Doom core     v3.0.0-p
To add an exception for this directory, call:

        git config --global --add safe.directory /nix/store/09391jc8xazy2mrjhmca0xzblrmxm9iz-source
Doom modules  v24.11.0-pre     fatal: detected dubious ownership in repository at '/nix/store/09391jc8xazy2mrjhmca0xzblrmxm9iz-source'
To add an exception for this directory, call:

        git config --global --add safe.directory /nix/store/09391jc8xazy2mrjhmca0xzblrmxm9iz-source
    ! Wrote extended backtrace to ~/.local/share/nix-doom/state/logs/cli.doom.241103232114.98372.error
✓ Finished in 0.63710s
```

Note: `/nix/store/09391jc8xazy2mrjhmca0xzblrmxm9iz-source/` is the `doomSource` and `/nix/store/ysr370j2nylqbvwmnk2y3w2hfm0w09ky-emacs-pgtk-29.4/` is the original Emacs I use for `programs.doom-emacs.emacs` (`pkgs.emacs29-pgtk`)

### Possible solution

Change `--init-directory` to a new directory (probably just a symlinkJoin) which would have the wrapped doom.
